#include "theme/Palettes.h"

namespace sub::ui {

namespace {

// "#rrggbb", and how opaque.
QColor hex(const char* rgb, int alpha = 255) {
    QColor color = QColor::fromString(QLatin1String(rgb));
    color.setAlpha(alpha);
    return color;
}

// SUBstation's own: dark, as the Python UI's theme was.
Palette defaultPalette() {
    return {
        .window = hex("#1c1c1c"),
        .panel = hex("#252525"),
        .panelAlt = hex("#2c2c2c"),
        .surface = hex("#363636"),
        .surfaceHover = hex("#404040"),
        .border = hex("#111111"),
        .text = hex("#d9d9d9"),
        .textDim = hex("#8e8e8e"),
        .textDisabled = hex("#5c5c5c"),
        .accent = hex("#ffa62b"),
        .accentText = hex("#1a1a1a"),
        .lane = hex("#2b2b2b"),
        .laneSelected = hex("#343434"),
        .emptyArea = hex("#222222"),
        .gridBar = hex("#4a4a4a"),
        .gridBeat = hex("#393939"),
        .gridSub = hex("#313131"),
        .playhead = hex("#f2f2f2"),
        .insertMarker = hex("#ffa62b"),
        .loopOn = hex("#c9c9c9"),
        .loopOff = hex("#5d5d5d"),
        .loopRegion = hex("#ffffff", 12),
        .selectionOutline = hex("#ffffff"),
        .selection = hex("#a8c8eb", 72),
        .rubberBand = hex("#ffa62b", 40),
        .waveform = hex("#161616", 230),
        .groupOutline = hex("#000000", 16),
        .deactivatedClip = hex("#8a8a8a"),
        .deactivatedContent = hex("#161616", 110),
        .keyWhite = hex("#d2d2d2"),
        .keyBlack = hex("#1f1f1f"),
        .keyLabel = hex("#4a4a4a"),
        .blackKeyRow = hex("#252525"),
        .outsideClip = hex("#000000", 110),
        .outOfKey = hex("#ff4a3d"),
        .pasteMarker = hex("#5cd6ff"),
        .volumeFill = hex("#ffa62b", 110),
        .activatorOn = hex("#ffc233"),
        .soloOn = hex("#4fa3ff"),
        .playOn = hex("#5fd35f"),
        .recordOn = hex("#ff5a4d"),
        .meterLow = hex("#3fcf55"),
        .meterMid = hex("#f2d024"),
        .meterHigh = hex("#ff4a3d"),
        .meterBg = hex("#141414"),
        .deviceHeader = hex("#3e3e3e"),
        .deviceHeaderSelected = hex("#577077"),  // teal (Ableton's)
        .deviceHeaderHover = hex("#ffffff", 28),
        .scopeLine = hex("#ffb84d"),
        .scopeGlow = hex("#ffa62b", 60),
        .scopeAxis = hex("#ffffff", 22),
        .frozen = hex("#8fd3ff"),
        .frozenTint = hex("#8fd3ff", 34),
        .knob = hex("#ffa62b"),
        .knobTrack = hex("#404040"),
        .scrollHandle = hex("#404040"),
        .scrollHandleHover = hex("#555555"),
        .automationOn = hex("#ff4a3d"),
        .automationOff = hex("#8c8c8c"),
    };
}

// Ableton Live 12's default theme (Dark), its colours read off Live itself:
// #363636 panels on a #2a2a2a desktop, #1e1e1e controls, #b5b5b5 text, the
// orange #ffad56 for what is on and the cyan #03c3d5 for knobs and markers.
Palette disabletonPalette() {
    return {
        .window = hex("#363636"),
        .panel = hex("#2a2a2a"),
        .panelAlt = hex("#3e3e3e"),
        .surface = hex("#1e1e1e"),
        .surfaceHover = hex("#2e2e2e"),
        .border = hex("#121212"),
        .text = hex("#b5b5b5"),
        .textDim = hex("#757575"),
        .textDisabled = hex("#575757"),
        .accent = hex("#ffad56"),
        .accentText = hex("#070707"),
        .lane = hex("#363636"),
        .laneSelected = hex("#434343"),
        .emptyArea = hex("#323232"),
        .gridBar = hex("#242424"),
        .gridBeat = hex("#2c2c2c"),
        .gridSub = hex("#313131"),
        .playhead = hex("#d6d6d6"),
        .insertMarker = hex("#03c3d5"),
        .loopOn = hex("#a3a3a3"),
        .loopOff = hex("#4a4a4a"),
        .loopRegion = hex("#ffffff", 10),
        .selectionOutline = hex("#ffffff"),
        .selection = hex("#b0ddeb", 70),
        .rubberBand = hex("#b0ddeb", 40),
        .waveform = hex("#181818", 230),
        .groupOutline = hex("#000000", 16),
        .deactivatedClip = hex("#757575"),
        .deactivatedContent = hex("#181818", 110),
        .keyWhite = hex("#c8c8c8"),
        .keyBlack = hex("#1e1e1e"),
        .keyLabel = hex("#575757"),
        .blackKeyRow = hex("#303030"),
        .outsideClip = hex("#000000", 90),
        .outOfKey = hex("#ff3636"),
        .pasteMarker = hex("#b0ddeb"),
        .volumeFill = hex("#007383"),
        .activatorOn = hex("#ffad56"),
        .soloOn = hex("#5d8de8"),
        .playOn = hex("#5ac55a"),
        .recordOn = hex("#ff3636"),
        .meterLow = hex("#0ccf5b"),
        .meterMid = hex("#ffd800"),
        .meterHigh = hex("#ff3636"),
        .meterBg = hex("#181818"),
        .deviceHeader = hex("#464646"),
        .deviceHeaderSelected = hex("#637e86"),
        .deviceHeaderHover = hex("#ffffff", 28),
        .scopeLine = hex("#03c3d5"),
        .scopeGlow = hex("#03c3d5", 60),
        .scopeAxis = hex("#ffffff", 22),
        .frozen = hex("#8fd3ff"),
        .frozenTint = hex("#8fd3ff", 34),
        .knob = hex("#03c3d5"),
        .knobTrack = hex("#181818"),
        .scrollHandle = hex("#575757"),
        .scrollHandleHover = hex("#757575"),
        .automationOn = hex("#c14541"),
        .automationOff = hex("#8c8c8c"),
    };
}

// Light: white controls on light grey, dark text.
Palette flashbangPalette() {
    return {
        .window = hex("#ececec"),
        .panel = hex("#dcdcdc"),
        .panelAlt = hex("#f7f7f7"),
        .surface = hex("#fdfdfd"),
        .surfaceHover = hex("#e6e6e6"),
        .border = hex("#a6a6a6"),
        .text = hex("#161616"),
        .textDim = hex("#5a5a5a"),
        .textDisabled = hex("#a8a8a8"),
        .accent = hex("#ff8a1f"),
        .accentText = hex("#161616"),
        .lane = hex("#f2f2f2"),
        .laneSelected = hex("#ffffff"),
        .emptyArea = hex("#e0e0e0"),
        .gridBar = hex("#a9a9a9"),
        .gridBeat = hex("#c8c8c8"),
        .gridSub = hex("#dadada"),
        .playhead = hex("#101010"),
        .insertMarker = hex("#ff8a1f"),
        .loopOn = hex("#4a4a4a"),
        .loopOff = hex("#b9b9b9"),
        .loopRegion = hex("#000000", 14),
        .selectionOutline = hex("#000000"),
        .selection = hex("#3c82dc", 60),
        .rubberBand = hex("#ff8a1f", 50),
        .waveform = hex("#161616", 230),
        .groupOutline = hex("#000000", 22),
        .deactivatedClip = hex("#b4b4b4"),
        .deactivatedContent = hex("#161616", 110),
        .keyWhite = hex("#ffffff"),
        .keyBlack = hex("#2b2b2b"),
        .keyLabel = hex("#8a8a8a"),
        .blackKeyRow = hex("#e2e2e2"),
        .outsideClip = hex("#000000", 45),
        .outOfKey = hex("#ff4a3d"),
        .pasteMarker = hex("#0a9bd6"),
        .volumeFill = hex("#ff8a1f", 110),
        .activatorOn = hex("#ffb000"),
        .soloOn = hex("#2f86ff"),
        .playOn = hex("#22b04a"),
        .recordOn = hex("#f0382b"),
        .meterLow = hex("#22b84a"),
        .meterMid = hex("#e8c200"),
        .meterHigh = hex("#f0382b"),
        .meterBg = hex("#cfcfcf"),
        .deviceHeader = hex("#d0d0d0"),
        .deviceHeaderSelected = hex("#9cc3cd"),
        .deviceHeaderHover = hex("#000000", 24),
        .scopeLine = hex("#e86f00"),
        .scopeGlow = hex("#ff8a1f", 60),
        .scopeAxis = hex("#000000", 26),
        .frozen = hex("#1f8fd8"),
        .frozenTint = hex("#1f8fd8", 34),
        .knob = hex("#ff8a1f"),
        .knobTrack = hex("#cfcfcf"),
        .scrollHandle = hex("#bdbdbd"),
        .scrollHandleHover = hex("#9a9a9a"),
        .automationOn = hex("#f0382b"),
        .automationOff = hex("#8c8c8c"),
    };
}

// Dark, purple-black, with the rainbow spread over what lights up: red
// records, orange activators, yellow the playhead, green loops and plays,
// cyan knobs and markers, blue solos, violet selections, pink the accent.
Palette gayPalette() {
    return {
        .window = hex("#17131c"),
        .panel = hex("#1f1a26"),
        .panelAlt = hex("#282133"),
        .surface = hex("#352c42"),
        .surfaceHover = hex("#42374f"),
        .border = hex("#0b080f"),
        .text = hex("#f2e9ff"),
        .textDim = hex("#a594b8"),
        .textDisabled = hex("#5e536b"),
        .accent = hex("#ff3fa4"),
        .accentText = hex("#14101a"),
        .lane = hex("#231d2b"),
        .laneSelected = hex("#2e2638"),
        .emptyArea = hex("#1b1621"),
        .gridBar = hex("#4c3f5c"),
        .gridBeat = hex("#3a3047"),
        .gridSub = hex("#2f2739"),
        .playhead = hex("#fff36b"),
        .insertMarker = hex("#3fe0ff"),
        .loopOn = hex("#7dff8a"),
        .loopOff = hex("#5b5068"),
        .loopRegion = hex("#7dff8a", 14),
        .selectionOutline = hex("#ffffff"),
        .selection = hex("#b278ff", 80),
        .rubberBand = hex("#ff3fa4", 45),
        .waveform = hex("#140e1a", 230),
        .groupOutline = hex("#000000", 16),
        .deactivatedClip = hex("#8a8090"),
        .deactivatedContent = hex("#140e1a", 110),
        .keyWhite = hex("#e8dcff"),
        .keyBlack = hex("#1c1724"),
        .keyLabel = hex("#6b5a80"),
        .blackKeyRow = hex("#1e1925"),
        .outsideClip = hex("#000000", 110),
        .outOfKey = hex("#ff4a3d"),
        .pasteMarker = hex("#7dff8a"),
        .volumeFill = hex("#ff3fa4", 110),
        .activatorOn = hex("#ff9a1f"),
        .soloOn = hex("#3f8cff"),
        .playOn = hex("#4cff6a"),
        .recordOn = hex("#ff2d55"),
        .meterLow = hex("#3fd0ff"),
        .meterMid = hex("#ffe83f"),
        .meterHigh = hex("#ff2d55"),
        .meterBg = hex("#120e17"),
        .deviceHeader = hex("#33293f"),
        .deviceHeaderSelected = hex("#7a3fc4"),
        .deviceHeaderHover = hex("#ffffff", 28),
        .scopeLine = hex("#ff5ec4"),
        .scopeGlow = hex("#b25cff", 70),
        .scopeAxis = hex("#ffffff", 22),
        .frozen = hex("#8fd3ff"),
        .frozenTint = hex("#8fd3ff", 34),
        .knob = hex("#3fe0ff"),
        .knobTrack = hex("#42374f"),
        .scrollHandle = hex("#4a3d5c"),
        .scrollHandleHover = hex("#6a5785"),
        .automationOn = hex("#ff2d55"),
        .automationOff = hex("#8c8c8c"),
    };
}

}  // namespace

const std::vector<NamedPalette>& palettes() {
    static const std::vector<NamedPalette> all = {
        {QStringLiteral("Default"), defaultPalette()},
        {QStringLiteral("Disableton"), disabletonPalette()},
        {QStringLiteral("Flashbang"), flashbangPalette()},
        {QStringLiteral("Gay"), gayPalette()},
    };
    return all;
}

}  // namespace sub::ui
