"""Writes browser/src/UnicodeTables.inc: the parts of Python's own text handling
the browser's search copies, taken from the running Python itself.

    python browser/tools/gen_unicode_tables.py

The native search has to match and order exactly as the Python code before it
did (str.lower, str.casefold, str.split, and the regex classes \\s and \\w), so
the tables are generated from those very functions rather than from the Unicode
data files. Re-run it with a newer Python to follow a newer Unicode version.

str.lower() maps U+03A3 (capital sigma) by its context (Final_Sigma). Python
decides that with two properties it doesn't expose, "cased" and
"case-ignorable"; they are read back here by lowering probe strings."""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "UnicodeTables.inc"
SIGMA = "Σ"
FINAL = "ς"


def ranges(predicate) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(0x110000):
        if predicate(chr(cp)):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def mapping(function) -> list[tuple[int, list[int]]]:
    out = []
    for cp in range(0x110000):
        c = chr(cp)
        if cp == 0x3A3:
            continue  # by context; see sigma()
        mapped = function(c)
        if mapped != c:
            assert 1 <= len(mapped) <= 3, (hex(cp), mapped)
            out.append((cp, [ord(m) for m in mapped]))
    return out


def sigma_properties(c: str) -> tuple[bool, bool]:
    """(case-ignorable, cased) as str.lower's Final_Sigma rule sees `c`. The
    cased property only matters for characters that aren't case-ignorable."""
    before_only = (c + SIGMA).lower().endswith(FINAL)  # not ignorable, and cased
    after_cased = ("A" + c + SIGMA).lower().endswith(FINAL)  # ignorable, or cased
    not_cased_after = ("A" + SIGMA + c).lower()[1] == FINAL  # ignorable, or not cased
    ignorable = not before_only and after_cased and not_cased_after
    cased = before_only
    if not ignorable:
        assert after_cased == cased and not_cased_after == (not cased), hex(ord(c))
    return ignorable, cased


def emit_ranges(name: str, rs: list[tuple[int, int]]) -> str:
    rows = ", ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in rs)
    return f"inline constexpr Range {name}[] = {{{rows}}};\n"


def emit_mapping(name: str, ms: list[tuple[int, list[int]]]) -> str:
    rows = []
    for cp, to in ms:
        padded = to + [0] * (3 - len(to))
        rows.append(f"{{0x{cp:X}, {{0x{padded[0]:X}, 0x{padded[1]:X}, 0x{padded[2]:X}}}, {len(to)}}}")
    return f"inline constexpr CaseMapping {name}[] = {{\n    " + ",\n    ".join(rows) + "};\n"


def main() -> None:
    ignorable, cased = [], []
    for cp in range(0x110000):
        i, c = sigma_properties(chr(cp))
        ignorable.append(i)
        cased.append(c and not i)
    text = [
        "// Generated by browser/tools/gen_unicode_tables.py; do not edit.\n",
        f"// Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.\n",
        "// Included by Text.cpp, inside its namespace.\n\n",
        f'inline constexpr const char* kUnicodeVersion = "{unicodedata.unidata_version}";\n\n',
        "// str.lower() of one character, where it changes (U+03A3 goes by its context).\n",
        emit_mapping("kLower", mapping(str.lower)),
        "\n// str.casefold() of one character, where it changes.\n",
        emit_mapping("kFold", mapping(str.casefold)),
        "\n// str.isspace(): what str.split() and the regex class \\s split on.\n",
        emit_ranges("kSpace", ranges(str.isspace)),
        "\n// The regex class \\w: str.isalnum() or '_'.\n",
        emit_ranges("kWord", ranges(lambda c: c.isalnum() or c == "_")),
        "\n// Case-ignorable characters, for the Final_Sigma rule of str.lower().\n",
        emit_ranges("kCaseIgnorable", [(a, b) for a, b in _runs(ignorable)]),
        "\n// Cased characters that are not case-ignorable, for the same rule.\n",
        emit_ranges("kCased", [(a, b) for a, b in _runs(cased)]),
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(text), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


def _runs(flags: list[bool]):
    start = None
    for cp, flag in enumerate(flags):
        if flag and start is None:
            start = cp
        elif not flag and start is not None:
            yield start, cp - 1
            start = None
    if start is not None:
        yield start, len(flags) - 1


if __name__ == "__main__":
    main()
